name: Create Release

on:
  push:
    tags:
      - v*

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Extract info
      id: info
      run: |
        node ./ci/extractInfo.js
      env:
        GITHUB_REF: ${{ github.ref }}
    - name: Create & upload artifact
      run: |
        npm install
        npm run dist:all
        go get -u github.com/tcnksm/ghr
        ./ci/bin/ghr -n "KataJigo v${{ steps.info.outputs.version }}" -prerelease ${{ steps.info.outputs.tag }} ./dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOPATH: ${{ steps.info.outputs.ci }}
